global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ousd_total_supply'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    metrics_path: /metrics/ousd_total_supply
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']

  - job_name: 'ousd_holdings_vault'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    metrics_path: /metrics/ousd_holdings_vault
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']

  - job_name: 'ousd_holdings_comp_strat'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    metrics_path: /metrics/ousd_holdings_comp_strat
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']

  - job_name: 'ousd_holdings_aave_strat'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    metrics_path: /metrics/ousd_holdings_aave_strat
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']

  - job_name: 'ousd_holdings_convex_strat'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    metrics_path: /metrics/ousd_holdings_convex_strat
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']

  - job_name: 'ousd_holdings_morpho_strat'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    metrics_path: /metrics/ousd_holdings_morpho_strat
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']

  - job_name: 'ousd_holdings_ousd_meta_strat'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    metrics_path: /metrics/ousd_holdings_ousd_meta_strat
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']

  # Example job for node_exporter
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  # Example job for cadvisor
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
